"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import sys
from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(DEBUG=(bool, False))
environ.Env.read_env(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DJANGO_DEBUG", default=False)

ALLOWED_HOSTS = env.list("DJANGO_ALLOWED_HOSTS", default=["localhost", "127.0.0.1"])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'market_data',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

if "test" in sys.argv:
    DATABASES = {"default": {"ENGINE": "django.db.backends.sqlite3", "NAME": ":memory:"}}
else:
    DATABASES = {"default": env.db("DATABASE_URL")}

CORS_ALLOWED_ORIGINS = env.list(
    "CORS_ALLOWED_ORIGINS", default=["http://localhost:5173"]
)

REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.AllowAny"],
}

SUPABASE_URL = env("SUPABASE_URL", default="")
SUPABASE_PUBLISHABLE_KEY = env("SUPABASE_PUBLISHABLE_KEY", default="")
PARLAY_API_KEY = env("PARLAY_API_KEY", default="")
PARLAY_API_BASE_URL = env(
    "PARLAY_API_BASE_URL", default="https://parlay-api.com/v1"
)
KALSHI_API_BASE_URL = env(
    "KALSHI_API_BASE_URL",
    default="https://api.elections.kalshi.com/trade-api/v2",
)
POLYMARKET_GAMMA_API_BASE_URL = env(
    "POLYMARKET_GAMMA_API_BASE_URL", default="https://gamma-api.polymarket.com"
)
POLYMARKET_CLOB_API_BASE_URL = env(
    "POLYMARKET_CLOB_API_BASE_URL", default="https://clob.polymarket.com"
)
MARKET_DATA_SPORTS = env.list(
    "MARKET_DATA_SPORTS",
    default=[
        "baseball_mlb",
        "americanfootball_nfl",
        "basketball_nba",
        "icehockey_nhl",
        "basketball_wnba",
        "soccer_epl",
    ],
)
MARKET_DATA_BOOKMAKERS = env.list(
    "MARKET_DATA_BOOKMAKERS",
    default=[
        "kalshi",
        "polymarket",
        "pinnacle",
        "fanduel",
        "novig",
        "prophetx",
        "bovada",
        "draftkings",
        "betmgm",
        "caesars",
        "betonline",
        "bet365",
        "betrivers",
        "fanatics",
        "fliff",
        "hardrock",
        "parx",
        "bookmaker_eu",
        "unibet",
        "tenbet",
        "betr",
        "sleeper",
        "pick6",
        "underdog",
        "prizepicks",
    ],
)
MARKET_DATA_MAX_AGE_SECONDS = env.int("MARKET_DATA_MAX_AGE_SECONDS", default=300)
MARKET_DATA_PROP_LIMIT = env.int("MARKET_DATA_PROP_LIMIT", default=10000)
MARKET_DATA_REQUEST_TIMEOUT_SECONDS = env.int(
    "MARKET_DATA_REQUEST_TIMEOUT_SECONDS", default=15
)
MARKET_DATA_MIN_EV_PERCENT = env.float("MARKET_DATA_MIN_EV_PERCENT", default=0.0)
MARKET_DATA_COST_ALLOWANCE_PERCENT = env.float(
    "MARKET_DATA_COST_ALLOWANCE_PERCENT", default=1.0
)
NESSIE_API_KEY = env("NESSIE_API_KEY", default="")
NESSIE_API_BASE_URL = env("NESSIE_API_BASE_URL", default="http://api.nessieisreal.com")
PERSONA_API_KEY = env("PERSONA_API_KEY", default="")
PERSONA_INQUIRY_TEMPLATE_ID = env("PERSONA_INQUIRY_TEMPLATE_ID", default="")
PERSONA_API_BASE_URL = env("PERSONA_API_BASE_URL", default="https://api.withpersona.com/api/v1")


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
