# Generated by Django 6.1.1 on 2026-09-12 03:38

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('persona_inquiry_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('verification_status', models.CharField(choices=[('not_started', 'Not started'), ('pending', 'Pending'), ('verified', 'Verified'), ('declined', 'Declined')], default='not_started', max_length=20)),
                ('is_age_verified', models.BooleanField(default=False)),
                ('markets', models.CharField(choices=[('kalshi', 'Kalshi'), ('polymarket', 'Polymarket'), ('both', 'Kalshi and Polymarket')], default='both', max_length=20)),
                ('bankroll', models.DecimalField(decimal_places=2, default=0, help_text='Amount the user has chosen to allocate for prediction markets.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_position_percent', models.DecimalField(decimal_places=2, default=5, help_text='Maximum percentage of bankroll allowed on one opportunity.', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_profiles',
            },
        ),
    ]
