# Generated by Django 6.1.1 on 2026-09-12 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='persona_event_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
