# Generated by Django 6.1.1 on 2026-09-12 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0003_enable_user_profile_rls'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='residence_country_code',
            field=models.CharField(blank=True, help_text='Persona-verified ISO 3166-1 alpha-2 country of residence.', max_length=2),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='residence_subdivision',
            field=models.CharField(blank=True, help_text='Persona-verified state, province, or region of residence.', max_length=64),
        ),
    ]
