# Generated by Django 6.1.1 on 2026-09-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0004_userprofile_residence_country_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='markets',
            field=models.CharField(choices=[('kalshi', 'Kalshi'), ('polymarket', 'Polymarket US'), ('both', 'Kalshi and Polymarket US')], default='both', max_length=20),
        ),
    ]
