# Generated by Django 6.1.1 on 2026-09-13 10:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


def enable_row_level_security(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute("ALTER TABLE saved_parlays ENABLE ROW LEVEL SECURITY")


def disable_row_level_security(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute("ALTER TABLE saved_parlays DISABLE ROW LEVEL SECURITY")


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0005_alter_userprofile_markets'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedParlay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Untitled parlay', max_length=120)),
                ('selections', models.JSONField(default=list)),
                ('estimated_edge', models.CharField(blank=True, max_length=32)),
                ('estimated_chance', models.CharField(blank=True, max_length=32)),
                ('position_sizing', models.JSONField(default=dict)),
                ('outcome', models.CharField(choices=[('pending', 'Pending'), ('won', 'Won'), ('lost', 'Lost')], default='pending', max_length=10)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(db_column='owner_uid', on_delete=django.db.models.deletion.CASCADE, related_name='saved_parlays', to='market_data.userprofile')),
            ],
            options={
                'db_table': 'saved_parlays',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(
            enable_row_level_security,
            reverse_code=disable_row_level_security,
        ),
    ]
